f_name=input("First name:")
l_name=input("Last name :")
grade=int(input("Grade 9-12:"))
id=int(input("Student ID:"))
log=input("Login     :")
gpa=float(input("GPA(0-4.0):"))
print("\n")
print("Your information")
print("{}Login :{}".format("     ",log))
print("{}ID    :{}".format("     ",id))
print("{}Name  :{},{}".format("     ",l_name,f_name))
print("{}GPA   :{}".format("     ",gpa))
print("{}Grade :{}".format("     ",grade))